# Alternative GitHub Actions workflow with different static analysis approach
# この設定ファイルは代替案として保存しておきます

name: C++ CI Alternative

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC Dev Environment
        uses: ilammy/msvc-dev-cmd@v1

      # MSVCの静的解析を使用する代替案
      - name: Build with MSVC Static Analysis
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug
          # MSVCの静的解析
          cl /analyze /EHsc /I.. ../main.cpp

      - name: Run tests
        run: ctest --test-dir build -C Debug
